# Generated by Django 6.0.2 on 2026-02-23 04:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
